; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rpipico2w]
; Target the community platform directly where Pico 2 W support is integrated
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board = rpipico2w

; Use the underlying Earle Philhower core automatically 
board_build.core = earlephilhower

; Serial speed matching your game project settings
monitor_speed = 9600

